# Generated by Django 2.1.7 on 2019-11-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client-register-first-name', models.CharField(max_length=40)),
                ('client-register-last-name', models.CharField(max_length=40)),
                ('client-register-middle-name', models.CharField(max_length=40)),
                ('client-register-dob', models.DateField()),
                ('client-register-gender', models.IntegerField()),
                ('client-register-password', models.CharField(max_length=50)),
                ('client-register-email', models.EmailField(max_length=254, unique=True)),
                ('client-register-SUO', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
