# Generated by Django 2.1.7 on 2019-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client-register-middle-name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
