# Generated by Django 2.1.7 on 2019-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191123_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client-register-dob',
            field=models.CharField(max_length=60),
        ),
    ]
