# Generated by Django 2.1.7 on 2019-11-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20191123_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client-register-gender',
            field=models.CharField(max_length=1),
        ),
    ]
