# Generated by Django 2.1.7 on 2019-11-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191123_0306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registration',
        ),
    ]
