# Generated by Django 2.1.7 on 2019-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20191123_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='U', max_length=1)),
                ('registration', models.IntegerField()),
                ('recorded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='user_recorded',
            field=models.IntegerField(default=-1),
        ),
    ]
