# Generated by Django 2.1.7 on 2019-11-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40, null=True)),
                ('dob', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('signed_up_on', models.DateTimeField(auto_now=True)),
                ('user_recorded', models.IntegerField(default=-1)),
            ],
        ),
    ]
